# Creating Special Arrays

### 1. np.zeros() ---> Array filled with 0

creates an array where all elements are 0.

In [3]:
import numpy as np

In [4]:
a = np.zeros((2,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
type(a)

numpy.ndarray

In [7]:
len(a)

2

In [8]:
a = np.zeros((5,9))
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


### 2. np.ones() ---> Array filled with 1

create an array where all elements are 1.

In [15]:
a = np.ones((3,2))
print(a)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [16]:
len(a)

3

In [17]:
a = np.ones((1,9))
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [18]:
len(a)

1

### 3. np.full() ----> Custom value Array

creates an array fulled with a specific value.

In [20]:
a = np.full((4,3),0.5)
print(a)

[[0.5 0.5 0.5]
 [0.5 0.5 0.5]
 [0.5 0.5 0.5]
 [0.5 0.5 0.5]]


In [21]:
a = np.full((8,4),5)
print(a)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


### 4. np.arange() ----> Range of values

Works like python range() but returnws an array 

**Formate : start : stop : size step**

In [22]:
a = np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [24]:
a = np.arange(5,55,5)
print(a)

[ 5 10 15 20 25 30 35 40 45 50]


### 5. np.linspace()  ---> Equal spacing

creates numbers evenly spaced between two values.

In [26]:
a = np.linspace(0,1,5)
print(a)

[0.   0.25 0.5  0.75 1.  ]


In [30]:
a = np.linspace(1,10,20)
print(a)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [31]:
a = np.linspace(-10,10,20)
print(a)

[-10.          -8.94736842  -7.89473684  -6.84210526  -5.78947368
  -4.73684211  -3.68421053  -2.63157895  -1.57894737  -0.52631579
   0.52631579   1.57894737   2.63157895   3.68421053   4.73684211
   5.78947368   6.84210526   7.89473684   8.94736842  10.        ]


In [32]:
a = np.linspace(1,100,20)
print(a)

[  1.           6.21052632  11.42105263  16.63157895  21.84210526
  27.05263158  32.26315789  37.47368421  42.68421053  47.89473684
  53.10526316  58.31578947  63.52631579  68.73684211  73.94736842
  79.15789474  84.36842105  89.57894737  94.78947368 100.        ]


### 6 .np.eye()  ----> Identity Matrix

creates a martix with 1s on diagonal, 0s elsewhere

very important in linear algebra

In [33]:
a = np.eye(4,4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [34]:
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [35]:
a = np.eye(2,4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]]


### 7. np.random.rand() ---> Random values (0 to 1).    Uniform Distribution

generates random numbers between 0 and 1.

In [36]:
import random

In [37]:
a = np.random.rand(2,4)
print(a)

[[0.6859768  0.80138646 0.49104629 0.49122016]
 [0.17999024 0.16421809 0.17447039 0.74944968]]


In [38]:
a = np.random.rand(3,3)
print(a)

[[0.03573499 0.69870867 0.90183705]
 [0.88485837 0.70166985 0.05615597]
 [0.72940947 0.46430011 0.54947179]]


### 8. np.random.randint() ---> Random integers

generates random integers in a given range

In [39]:
a = np.random.randint(1,10,(2,3))
print(a)

[[5 2 2]
 [7 4 2]]


In [40]:
a = np.random.randint(1,10,(2,3))
print(a)

[[3 9 4]
 [4 9 1]]


In [41]:
a = np.random.randint(1,10,(2,3))
print(a)

[[8 5 3]
 [2 8 8]]


### 9. np.random.randn() ---> Random numbers (-infinity to +infinity) .     Normal Distribution (Gaussian)

randn() generates numbers from a standard normal distribution

**Syntax :- np.random.randn(d0 , d1, ......., dn)

In [42]:
a = np.random.randn(5)
print(a)

[-2.73325006  0.18531198 -0.33113825 -1.21735368 -0.13047303]


In [43]:
a = np.random.randn(5)
print(a)

[-1.26556283  0.15206326  0.58393046  1.27829594  0.79061319]


In [45]:
a = np.random.randn(10)
print(a)

[-1.25554231  1.51111082  2.69462185 -0.55947439  1.33505864  1.46047764
  0.27903417 -1.77324994 -0.31939347 -0.19211996]


In [46]:
a = np.random.randn(100)
print(a)

[-0.04698258  0.52485327  0.62787793 -0.23682207  0.47113021  0.69591863
  1.38920405 -0.77576385  0.27925359  0.18024402  0.29984544  0.19222719
  1.64876657 -0.2070586   1.94757692  1.11429377 -0.29709242 -0.41982056
 -0.83244129  0.14177998  1.04735105  0.14108912  0.16718437  1.00163767
 -0.29381407  1.42905852  0.20350561 -0.3564218   0.22017642  0.6831612
  0.23432255  1.23463836 -0.90017882  0.79020007 -1.50981582  0.32613951
  0.73589871 -1.0924574  -0.90713496  1.15455856  0.99387065  0.32067618
 -1.07694206 -1.68686021 -0.49577464  1.56506074 -0.72323182  0.84004847
  1.370078   -0.10319956  0.37806319  0.14514719 -0.0271155  -1.6247256
 -1.00975836 -0.22763062 -0.50912975 -0.91158538 -1.00846845 -0.72962241
  0.03730227  0.63392727  0.02210146 -0.74265045 -2.14871056 -0.32503972
  0.43013034  1.73861873  2.20648035  0.19826777  0.85516923  0.56110393
 -0.7462441  -0.42859564  0.21128553  2.27101609  0.36285882  0.92197965
  0.39597901 -0.83767704 -0.15045287  0.61569239 -0.7

In [48]:
a = np.random.randn(500)
print(a)

[ 2.86007421  1.89330036 -0.58029828 -0.15032521 -0.86822372 -0.08219477
 -0.6355475  -1.29715193  0.33486762  2.53025562  0.57107255 -0.9723863
  0.44033623 -0.21364162 -0.61236879 -0.67542295 -0.49423896  1.01182942
 -0.14592944  0.07591319  1.69440863 -0.76210439 -1.02770213 -0.35211042
 -0.41832234 -1.20340993 -0.82456423 -1.11325719 -1.7127406   0.67770987
  1.03657708  0.54071673  0.59303118  0.33847224  0.09893653  1.26436537
 -0.27828428 -0.41705912  0.42318679 -0.3634779  -0.68549851  1.03306227
 -0.9089415  -1.04049376  0.96247587 -2.34623581 -0.41081375 -0.15389383
  1.67013704  0.01441324 -1.6914163  -0.4221584  -1.35649155 -1.31792094
 -0.09054152 -0.2772579   0.20552679 -0.47422862 -1.25170506 -0.63754162
 -0.38257159  1.5437296  -0.23693454  0.22821524  1.34295327 -0.60555045
 -0.14162356  1.30021374  0.2037293  -0.84281263 -1.269764   -0.37738822
  0.42161625 -0.32781405  0.81003605  0.39984459 -0.02174893  0.41702076
 -0.44194271  1.3815542   0.16702536 -1.18189586 -0.