In [3]:
import numpy as np

#### In NumPy , the main object is called ndarray(N-Dimension Array).

# Creating Array

In [4]:
arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


### 1-D Array

Looks like a single row

Similar to a normal list

In [5]:
a = np.array([1,2,3])

In [6]:
print(a)

[1 2 3]


In [7]:
a = np.array([2])
print(a)

[2]


In [8]:
type(print(a))

[2]


NoneType

### 2-D  Array

Rows & Columns

Looks like a matrix

In [9]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [10]:
b = np.array([[1,2,3]])
print(b)

[[1 2 3]]


### 3-D Array

Multiple 2D arrays stacked together.

Used in images, deep learning , etc.

In [11]:
c = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(c)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [12]:
c = np.array([[[1,2,3]]])
print(c)

[[[1 2 3]]]


In [13]:
c = np.array([[[1,2,3],[5,6,7]]])
print(c)

[[[1 2 3]
  [5 6 7]]]


# Attributes

### ndim (number of dimension) :-

tells how many dimensions the array has

In [14]:
print(a)

[2]


In [15]:
print(a.ndim)

1


In [16]:
print(b)

[[1 2 3]]


In [17]:
print(b.ndim)

2


In [18]:
print(c)

[[[1 2 3]
  [5 6 7]]]


In [19]:
print(c.ndim)

3


### shape (structure of array) :-

how many (rows and columns)

In [20]:
print(a.shape)

(1,)


In [21]:
print(b.shape)

(1, 3)


In [22]:
print(c.shape)

(1, 2, 3)


In [23]:
c = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(c)


[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [24]:
print(c.ndim)

3


In [25]:
print(c.shape)

(1, 3, 3)


### size (total number of elements) :-

Rows x Columns = 2*3 = 6

In [26]:
print(a.size)

1


In [27]:
print(b.size)

3


In [28]:
print(c.size)

9


### dtype (data types of elements) :-

int32, float64, bool ,object

In [29]:
print(a.dtype)

int32


In [30]:
print(b.dtype)

int32


In [31]:
x = np.array([1.23,78,23.4])
print(x.dtype)

float64


In [32]:
c = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(c)


[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [33]:
print(c.dtype)

int32


In [34]:
c = np.array([[[1,2,3],[4,5,6],[7,8,9]]],dtype = float)
print(c)
print(c.dtype)

[[[1. 2. 3.]
  [4. 5. 6.]
  [7. 8. 9.]]]
float64


### itemsize (memory used each elements) 

In [35]:
a

array([2])

In [36]:
b

array([[1, 2, 3]])

In [37]:
c

array([[[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]])

In [38]:
print(a.itemsize)

4


In [39]:
print(b.itemsize)

4


In [40]:
print(c.itemsize)

8


# Data Types Conversion in NumPy (astype())

### **Syntax :- array.astype(new_dtype)**

#### integer -----> float

In [43]:
a = np.array([1,2,3])
new_a = a.astype(float)
print(new_a)

[1. 2. 3.]


In [44]:
print(new_a.dtype)

float64


#### float ------> integer

In [45]:
b = np.array([12.3, 67.3, 278.8])
b2 = b.astype(int)
print(b2)

[ 12  67 278]


In [46]:
print(b2.dtype)

int32


#### convert to string

In [47]:
a = np.array([10,70,30])
a2 = a.astype(str)
print(a2)

['10' '70' '30']


In [48]:
print(a2.dtype)

<U11


#### convert to boolean

In [51]:
a = np.array([0,1,4,0,3,0])
a2 = a.astype(bool)
print(a2)

[False  True  True False  True False]


In [52]:
print(a2.dtype)

bool


In [53]:
print(a2)

[False  True  True False  True False]


#### convert to specific types(int32, float32)

In [55]:
a = np.array([1,2,3,4])
print(a)
print(a.dtype)

[1 2 3 4]
int32


In [58]:
a2 = a.astype(np.float32)
print(a2)
print(a2.dtype)

[1. 2. 3. 4.]
float32
