# NumPy Operations

### 1. Arithmetic Operations 

Numpy performs elements-wise operations on arrays

In [1]:
import numpy as np

In [2]:
a = np.array([10,20,30])
b = np.array([1,2,3])

In [3]:
print(a+b)

[11 22 33]


In [4]:
print(a-b)

[ 9 18 27]


In [5]:
print(a*b)

[10 40 90]


In [6]:
print(a/b)

[10. 10. 10.]


In [7]:
print(a%b)

[0 0 0]


### 2. Comparison Operations

used to compaare elements --> returns Boolean array (True/False)

In [8]:
a = np.array([10,20,30,40])

In [9]:
print(a>15)

[False  True  True  True]


In [10]:
print(a<10)

[False False False False]


In [11]:
print(a=10)

TypeError: 'a' is an invalid keyword argument for print()

In [12]:
print(a==10)

[ True False False False]


In [14]:
b = a%2==0
print(b)

[ True  True  True  True]


##### used for filtering (Boolean Indexing)

In [15]:
print(a[a>15])

[20 30 40]


In [16]:
print(a>15)

[False  True  True  True]


### 3. Logical Operations

used to combine multiple conditions



In [17]:
a = np.array([11,22,33,44])

In [18]:
print((a>15) & (a<35))

[False  True  True False]


##### using function

In [19]:
a = np.logical_and(a>15,a<35)
print(a)

[False  True  True False]


In [21]:
b = np.logical_or(a>25 , a<15)
print(b)

[ True  True  True  True]


In [ ]:
c = np.logical_not(a>20)